version: '3.8'

services:
  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - microservices-network

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - microservices-network

  broker:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - authentication-service=microservice1:8080
      - product-service=microservice2:8081
      - cart-service=cartservice:8082
    depends_on:
      - authentication-service
      - product-service
      - cart-service
    networks:
      - microservices-network

# Define the network to be used by the microservices for inter-communication
networks:
  microservices-network:
    driver: bridge
