version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./docker/postgres_data:/data/postgres
    environment:
      POSTGRES_DB: zcommerce
      POSTGRES_USER: zcommerce_user
      POSTGRES_PASSWORD: admin123!#mlooa98\\
    ports:
      - "5432:5432"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  web:
    build: ./ecommerce
    volumes:
      - ./ecommerce:/ecommerce
    ports:
      - "8001:8001"
    depends_on:
      - db
      - dynamodb-local
    links:
      - "dynamodb-local"
    environment:
      - POSTGRES_DB=zcommerce
      - POSTGRES_USER=zcommerce_user
      - POSTGRES_PASSWORD=admin123!#mlooa98\\
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgres://zcommerce_user:admin123!#mlooa98\\@db:5432/zcommerce
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=dummy_key
      - AWS_SECRET_ACCESS_KEY=dummy_secret
      - AWS_DEFAULT_REGION=your-region

volumes:
  postgres_data:
