# Generated by Django 5.0.1 on 2024-02-05 19:47

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_companyprofile_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubscription',
            fields=[
            ],
            options={
                'permissions': [('is_registered', 'Has registered a company'), ('can_publish_products', 'Can publish products'), ('can_process_orders', 'Can process orders')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SimpleSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('can_use_client_chat', 'Can use client chat'), ('can_backup_items', 'Can backup items')],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.basesubscription',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MediumSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('can_promote_products', 'Can promote products')],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.simplesubscription',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('can_use_analytics', 'Can use analytics'), ('can_request_helpdesk_bot', 'Can request helpdesk bot')],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.mediumsubscription',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
