# Generated by Django 5.0.1 on 2024-02-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_basesubscription_simplesubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.companyprofile'),
        ),
    ]
