# Generated by Django 5.0.1 on 2024-01-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title', 'created_at')},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
