# Generated by Django 5.0.1 on 2024-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamoDbTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aws_region', models.CharField(max_length=50)),
                ('aws_endpoint_url', models.URLField()),
                ('aws_access_key_id', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DynamoDB Table',
                'verbose_name_plural': 'DynamoDB Tables',
            },
        ),
    ]
